version: 2

models:
  - name: raw_wsj
    description: "Combined Wall Street Journal gainer rows for Spring‑Break week"
    columns:
      - name: SYMBOL
        description: "Ticker symbol"
      - name: PRICE
      - name: PRICE_CHANGE
      - name: PRICE_PERCENT_CHANGE

  - name: raw_yahoo
    description: "Combined Yahoo Finance gainer rows for Spring‑Break week"
    columns:
      - name: SYMBOL
      - name: PRICE
      - name: PRICE_CHANGE
      - name: PRICE_PERCENT_CHANGE

  - name: weekly_agg_wsj
    description: "Weekly averages for WSJ gainers"
    columns:
      - name: WEEK_NUMBER
      - name: AVG_PRICE
      - name: AVG_PRICE_CHANGE
      - name: AVG_PRICE_CHANGE_PERCENT

  - name: weekly_agg_yahoo
    description: "Weekly averages for Yahoo gainers"
    columns:
      - name: WEEK_NUMBER
      - name: AVG_PRICE
      - name: AVG_PRICE_CHANGE
      - name: AVG_PRICE_CHANGE_PERCENT

  - name: final_summary_wsj
    description: "Final WSJ summary ‑ unique counts and extremes"
    columns:
      - name: WEEK_NUMBER
      - name: TOTAL_UNIQUE_STOCKS
      - name: AVERAGE_WEEKLY_PRICE
      - name: MAX_PRICE_CHANGE
      - name: MAX_PRICE_CHANGE_PERCENT

  - name: final_summary_yahoo
    description: "Final Yahoo summary ‑ unique counts and extremes"
    columns:
      - name: WEEK_NUMBER
      - name: TOTAL_UNIQUE_STOCKS
      - name: AVERAGE_WEEKLY_PRICE
      - name: MAX_PRICE_CHANGE
      - name: MAX_PRICE_CHANGE_PERCENT

  - name: repeated_symbols_wsj
    description: "Stocks that appeared more than once in WSJ gainers list"
    columns:
      - name: SYMBOL
      - name: APPEARANCE_COUNT

  - name: repeated_symbols_yahoo
    description: "Stocks that appeared more than once in Yahoo gainers list"
    columns:
      - name: SYMBOL
      - name: APPEARANCE_COUNT

