name: Feature Validation 2

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make update
      - name: Pylint check
        run: |
          make lint  # this is failing in the github action -> https://github.com/KanittaSrichan/SP25_DS5111_uay3yb/actions/runs/14369351720/job/40289306202
                     # it's not finding the pylint program, so maybe the makefile is not setting the virtual environment?
      - name: Test with pytest
        run: |
          make test
